# v3 syntax
version: '3'

services:

  postgres:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pokemon_battle_db
